### PR TITLE
Defined installation instructions to run Jupyter Notebook with environment having cantera package

### PR DESCRIPTION
**Pull request by funnelferry**

### CODE REVIEW

**Comment by funnelferry** [comment]
@bryanwweber Hello Bryan, I made this PR 3 days ago, I hope you can look into it and suggest edits.

**Comment by speth** [comment]
I would rather not duplicate the instructions that are maintained at https://cantera.org/install/conda-install.html. Perhaps adding a link to this specific page and suggesting that Conda is the easiest installation path would be useful, in addition to the link to the general installation instructions.

**Comment by funnelferry** [comment]
@speth I see, but the the instruction at the website do not contain the part guiding the user to properly run Jupyter Notebook in environment having cantera package without which it would result in 'Module not found' error. Maybe adding a link and then putting the notebook setup under a Note title can be preffered?

**Comment by bryanwweber** [comment]
@funnelferry I updated the instructions to be more like what I had in mind. Let me know what you think!

**Comment by bryanwweber** [comment]
I wonder if it might be better to tell people to use the `environment.yml` file to create a conda environment

```
git clone https://github.com/Cantera/cantera-jupyter.git  # or download the zip file
cd cantera-jupyter  # or unzip and cd
conda env create -f environment.yml
conda activate cantera-latest
conda install notebook
jupyter notebook
```
Since pandas and matplotlib are required to run these examples

**Comment by funnelferry** [comment]
@bryanwweber It looks neat, and as long as it conforms to what you would want it to look like it's great :)

Using `environment.yml` is certainly better, Infact why not replace the instructions with just use of yml file for creating the environment so all the required packages are installed in a single step? I have all the required the packages install in my environment and I exported them to a updated yml file. Should I make a PR updating the existing environment.yml file? and update the instructions in README.md?

**Comment by bryanwweber** [comment]
I'm fine with these changes as-is. @speth Any other comments?

**Review by bryanwweber — APPROVED** [review]

**Pull request merged**
