### PR TITLE
Add notebook illustrating conversion of CHEMKIN files via ck2yaml

### PR DESCRIPTION
**Pull request by ischoegl**
This PR collects CHEMKIN input files previously used in Cantera (i.e. < version 2.5.0a4) and re-creates the following YAML files from scratch.

*GRI-Mech 3.0 derived:*

* `gri30_demo.yaml` (corresponds to `gri30.yaml` without deprecated phases)
* `h2o2_demo.yaml` (corresponds to `h2o2.yaml`)
* `air_demo.yaml` (corresponds to `air.yaml`)
* `argon_demo.yaml` (corresponds to the - now deprecated - `argon.yaml`)

*NASA derived:*

* `airNASA9_demo.yaml` (corresponds to `airNASA9.yaml`)
* `nasa_demo.yaml` (corresponds to `nasa.yaml`)

**Motivation:**

The example serves two purposes:
1. Illustrate usage of `ck2yaml`
2. Document heritage of input files

**Other:**

* Comments are currently rudimentary; if this PR is of interest, they will be augmented.
* Some of the original input files were missing a header block, which was added for clarity. If Cantera/cantera#794 (`--extra` option) is merged, this change can be reversed, while still creating a header that corresponds to stock cantera yaml input.

### CODE REVIEW

**Comment by bryanwweber** [comment]
@ischoegl Does this need to be updated to resolve your comments above about Cantera/cantera#794?

**Comment by ischoegl** [comment]
@bryanwweber ... it likely does. With all that time passing I had honestly forgotten about this. Shouldn’t take too long, but it’s not a priority for me at the moment.

What’s the current game plan for 2.5? (I noticed that PR review activity slowed down on the main repo). I was hoping for the HDF5 review as the pandas solution is sub-optimal ... other than that, I’m mostly done with my contributions.

**Comment by bryanwweber** [comment]
Yeah, no problem if this takes a little while. I'm working on a burn down list of high-priority stuff for 2.5, my objective is to get a beta out ASAP... Subject of course to other work interfering, as always 😁

**Comment by ischoegl** [comment]
@bryanwweber ... Good to know. Any chance to get Cantera/cantera#840 added prior to beta? It’d be good if the stand-in HDF implementation never makes it to beta. I think that @speth’s comments in Cantera/cantera#830 do have a point.

**Comment by ischoegl** [comment]
@bryanwweber ... I updated this PR.

**Pull request merged**
