### PR TITLE
Well stirred reactor

### PR DESCRIPTION
**Pull request by santoshshanbhogue**
This example shows how to simulate well-stirred reactors in a way that enables comparison with experiments.

### CODE REVIEW

**Comment by santoshshanbhogue** [comment]
Hello... Anybody home ?

**Comment by speth** [comment]
- Please make Python 3 the default kernel (this will enable this example to work on Binder, among other things)
- In the intro, I think it is better to just write "Continuously Stirred Tank Reactor (CSTR)" instead of using bold. That way spell check can catch some of your misspellings (like Continuouly). Also you switch from singular to plural in the middle of your list of names for the WSR.
- In the diagram, I think the notation `mdot(t=0)` and `mdot(t=tau)` at the inlet/outlet are confusing. First, Cantera always solves the unsteady problem, where mdot itself is a function of time, and `mdot(t)` would be the normal notation for this. Second, tau is the *average* residence time; a unit of mass leaving the reactor will be partly composed of matter that has been in the reactor longer and shorter than the average. The way this is labeled looks more like what you would expect from a PFR.
- The idea that m is computed as PV/RT is misleading. In all of Cantera's models, the mass is a state variable and it's either the pressure or volume that is computed using the ideal gas law. Also, if your diagram is supposed to be indicating the state variables, then it should include the mass fractions in that list.

- Conditional statements should not be written with extra parentheses. For example:
```python
while((counter < maxSteps) and (t < maxSimulationTime)):
```
should be written as
```python
while counter < maxSteps  and t < maxSimulationTime:
```
- I'm not sure that terminating based on a maximum number of steps is a good idea. It has no physical meaning, but just reflects numerical properties of the solution method. Some multiple of the residence time is the only sensical stopping condition.
- Please convert the XLSX spreadsheet to CSV.
- Using backslashes is [generally discouraged](https://www.python.org/dev/peps/pep-0008/#maximum-line-length), and unnecessary when inside a grouping delimiter (e.g. parentheses). So the following:
```python
pressureRegulator = ct.Valve(upstream=stirredReactor,\
                             downstream=exhaust,\
                             K=pressureValveCoefficient)
```
Can just be written as:
```python
pressureRegulator = ct.Valve(upstream=stirredReactor,
                             downstream=exhaust,
                             K=pressureValveCoefficient)
```
- I think I would recommend against using `ReactorNet.get_state()` in most situations. If you want to capture specific state variables, just access the relevant properties of `stirredReactor` or `stirredReactor.thermo` as necessary.
- `+=` gets space around it, like any other operator, so
```python
counter+=1
```
should be
```python
counter += 1
```
- In the loop in `[7]`, you're only storing every 10th value, so you may as well only build `state` inside the `if` condition (which can just be written as `if not counter % 10`)
- In figure 1, you got the entire Y label in math mode
- In figure 2, is it more correct to say that the y scale is "x 10^-3" or "x 10^3"? Honestly, I always have a bit of trouble parsing this notation; maybe floating point notation on this axis would be better?
- These examples take quite a while to run on my computer (~90 seconds per steady-state solve; I guess you ran them with a parallel BLAS), and I'm guessing they will be even slower on Binder. It's probably adding a comment that noting that the simulations will take a bit of time.
- One thing that will speed up the subsequent calculations in the loop over temperature is to re-use the mole fraction vector from the previous iteration in the initial reactor state, since this is a better approximation for the steady-state solution than the composition of the inlet mixture.

**Comment by santoshshanbhogue** [comment]
Please make Python 3 the default kernel (this will enable this example to work on Binder, among other things)
-- Done

In the intro, I think it is better to just write "Continuously Stirred Tank Reactor (CSTR)" instead of using bold. That way spell check can catch some of your misspellings (like Continuouly). Also you switch from singular to plural in the middle of your list of names for the WSR.
-- Done

In the diagram, I think the notation mdot(t=0) and mdot(t=tau) at the inlet/outlet are confusing. First, Cantera always solves the unsteady problem, where mdot itself is a function of time, and mdot(t) would be the normal notation for this. Second, tau is the average residence time; a unit of mass leaving the reactor will be partly composed of matter that has been in the reactor longer and shorter than the average. The way this is labeled looks more like what you would expect from a PFR.
The idea that m is computed as PV/RT is misleading. In all of Cantera's models, the mass is a state variable and it's either the pressure or volume that is computed using the ideal gas law. Also, if your diagram is supposed to be indicating the state variables, then it should include the mass fractions in that list.
-- Changed label to remove ambiguity due to "average" residence time and removed formula for mass

Conditional statements should not be written with extra parentheses. For example:
`while((counter < maxSteps) and (t < maxSimulationTime)):`
should be written as
`while counter < maxSteps  and t < maxSimulationTime:`
-- Done

I'm not sure that terminating based on a maximum number of steps is a good idea. It has no physical meaning, but just reflects numerical properties of the solution method. Some multiple of the residence time is the only sensical stopping condition.
-- Agreed; changed. 

Please convert the XLSX spreadsheet to CSV.
-- Done


Using backslashes is generally discouraged, and unnecessary when inside a grouping delimiter (e.g. parentheses). So the following:
```
pressureRegulator = ct.Valve(upstream=stirredReactor,\
                             downstream=exhaust,\
                             K=pressureValveCoefficient)
```
Can just be written as:
```
pressureRegulator = ct.Valve(upstream=stirredReactor,
                             downstream=exhaust,
                             K=pressureValveCoefficient)
```
-- Changed

I think I would recommend against using ReactorNet.get_state() in most situations. If you want to capture specific state variables, just access the relevant properties of stirredReactor or stirredReactor.thermo as necessary.
-- Removed `ReactorNet.get_state()`

+= gets space around it, like any other operator, so
`counter+=1`
should be
`counter += 1`
-- Done

In the loop in [7], you're only storing every 10th value, so you may as well only build state inside the if condition (which can just be written as if not counter % 10)
-- Good idea. Done

In figure 1, you got the entire Y label in math mode
-- Changed. Put only the symbols in math mode

In figure 2, is it more correct to say that the y scale is "x 10^-3" or "x 10^3"? Honestly, I always have a bit of trouble parsing this notation; maybe floating point notation on this axis would be better?
-- Removed "x 10^-3" in the labeling. I did this because the paper published data this way. I thought it may facilitate a better comparison

These examples take quite a while to run on my computer (~90 seconds per steady-state solve; I guess you ran them with a parallel BLAS), and I'm guessing they will be even slower on Binder. It's probably adding a comment that noting that the simulations will take a bit of time.
-- I checked my cantera.conf file and I did not build with BLAS. Used the default Eigen libraries. And 90 seconds on your computer? Really? 

One thing that will speed up the subsequent calculations in the loop over temperature is to re-use the mole fraction vector from the previous iteration in the initial reactor state, since this is a better approximation for the steady-state solution than the composition of the inlet mixture.
-- You mean something like this:
```
    if i == 0:
        concentrations = {'NC7H16': 0.005, 'O2': 0.0275, 'HE': 0.9675}
        gas.TPX = reactorTemperature, reactorPressure, concentrations 
    else:
        gas.TP = reactorTemperature, reactorPressure
```
-- I get convergence issues for some cases (Cantera error)

**Comment by speth** [comment]
Please don't make merge commits within a PR; it makes it harder to isolate the changes introduced by the PR. If you need to incorporate changes from master, you can rebase the PR onto the current master.

**Comment by santoshshanbhogue** [comment]
Noted

**Comment by speth** [comment]
Thanks for the updates.

- When I try to launch the notebook, I get an error:
```
I couldn't find a kernel matching p3. Please select a kernel:
```
I don't understand all of the ins and outs of Jupyter kernels, but I think the `.ipynb` file should specify the kernel as having the `name` as `python3` and the `display_name` as `Python 3`. Not sure why your kernels are named differently than this.
- I think you forgot to add the `.csv` file and remove the `.xlsx` file in your commit.
- There's still one unnecessary trailing `\`
- The previous suggestion about parentheses in `while` statements also applies to `if` statements.
- In `In [12]`, the variable `i` is never used, so you can drop the `enumerate`.
- You can build `state` in one step:
```python
state = np.hstack([stirredReactor.thermo.P, stirredReactor.mass, 
                   stirredReactor.volume, stirredReactor.T, stirredReactor.thermo.X])
```
- I had some issues with convergence at one temperature, not sure why, but reducing the valve coefficient to 0.01 seems to fix it, and has no impact on the results (even this is a fairly large coefficient given the small reactor volume).
- In order to restart with the old composition, you need to stash it in a variable, set up the inlet object, restore the composition, then create the reactor. What I'm suggesting is a loop that looks something like:
```python
inlet_composition = {'NC7H16': 0.005, 'O2': 0.0275, 'HE': 0.9675}
composition = inlet_composition
for temperature in T:
    ...
    gas.TPX = reactorTemperature, reactorPressure, inlet_composition
    ...
    fuelAirMixtureTank = ct.Reservoir(gas)
    exhaust = ct.Reservoir(gas)
    gas.TPX = reactorTemperature, reactorPressure, composition
    stirredReactor = ct.IdealGasReactor(gas, energy='off', volume=reactorVolume)
    ...
    composition = stirredReactor.thermo.X
```

**Comment by santoshshanbhogue** [comment]
When I try to launch the notebook, I get an error:
I couldn't find a kernel matching p3. Please select a kernel:
I don't understand all of the ins and outs of Jupyter kernels, but I think the .ipynb file should specify the kernel as having the name as python3 and the display_name as Python 3. Not sure why your kernels are named differently than this.
-- It will take me a while to reinstall/rename the kernel, etc. For just this commit, can you change this for me? For future commits I'll test python3

I think you forgot to add the .csv file and remove the .xlsx file in your commit.
There's still one unnecessary trailing \
-- Fixed (in cell 12)

The previous suggestion about parentheses in while statements also applies to if statements.
In In [12], the variable i is never used, so you can drop the enumerate.
You can build state in one step:
```
state = np.hstack([stirredReactor.thermo.P, stirredReactor.mass, 
                   stirredReactor.volume, stirredReactor.T, stirredReactor.thermo.X])
```
-- Fixed in cells 7 and 12

I had some issues with convergence at one temperature, not sure why, but reducing the valve coefficient to 0.01 seems to fix it, and has no impact on the results (even this is a fairly large coefficient given the small reactor volume).
-- For me, both 1.0 and 0.01 work. So I have changed it to 0.01

In order to restart with the old composition, you need to stash it in a variable, set up the inlet object, restore the composition, then create the reactor. What I'm suggesting is a loop that looks something like:
```
inlet_composition = {'NC7H16': 0.005, 'O2': 0.0275, 'HE': 0.9675}
composition = inlet_composition
for temperature in T:
    ...
    gas.TPX = reactorTemperature, reactorPressure, inlet_composition
    ...
    fuelAirMixtureTank = ct.Reservoir(gas)
    exhaust = ct.Reservoir(gas)
    gas.TPX = reactorTemperature, reactorPressure, composition
    stirredReactor = ct.IdealGasReactor(gas, energy='off', volume=reactorVolume)
    ...
    composition = stirredReactor.thermo.X
```
-- I tried this and it does not change the simulation times, but makes the comparison between models and expts. worse. I think it is also pedagogically unwise to do this. Because unless the user is a seasoned cantera user, he/she will definitely run the code twice - one with using compositions from the prior simulations and one reinitializing to the inlet composition of experiment...

**Comment by santoshshanbhogue** [comment]
Also, I changed the README.md file. Just want to make sure you did not miss this in the wake of the merge-commit fiasco

**Comment by speth** [comment]
I saw the updated readme, and that looks fine.

I will fix the Python version before I push the commit.

I'm not sure exactly how you implemented the changes, but if changing the initial condition changes the steady state result, then the system is not correctly being integrated to steady state solution and that needs to be investigated. The code that I wrote above will give the same answer if run twice, so I'm not sure I understand your concern. In general, I think it is a good idea to show that integrating from a relatively nearby steady-state is faster than starting from scratch every time (and if that's not what you're seeing in the timings, at least overall, if not for every individual temperature, then I think you might have had a bug in your implementation). I'm fairly certain that I was getting the same results either way when I tried this.

Another few small things I noticed:
- in `In[12]`, the variable `timeHistory` is used in a fairly useless way. You could eliminate it entirely and just save the end state by writing `tempDependence.loc[temperature] = state`.
- In the comment "If not, go back and adjust max. number of steps and/or simulation time", the reference to number of steps should be removed since we aren't stopping the simulation based on this anymore

**Comment by santoshshanbhogue** [comment]
Hmm... I am now running this on my office Mac-desktop and the simulation indeed takes 80+ seconds. I could swear I installed this with the same cantera.conf file, but not sure why...

Response to your comments:

I saw the updated readme, and that looks fine.
-- Great

I will fix the Python version before I push the commit.
-- Thanks

I'm not sure exactly how you implemented the changes, but if changing the initial condition changes the steady state result, then the system is not correctly being integrated to steady state solution and that needs to be investigated. The code that I wrote above will give the same answer if run twice, so I'm not sure I understand your concern. In general, I think it is a good idea to show that integrating from a relatively nearby steady-state is faster than starting from scratch every time (and if that's not what you're seeing in the timings, at least overall, if not for every individual temperature, then I think you might have had a bug in your implementation). I'm fairly certain that I was getting the same results either way when I tried this.
-- I made a typo in my implementation, hence saw erroneous results. I have now used your suggestion and see a speedup without loss of accuracy. Made the change in the revised version

Another few small things I noticed:

* in In[12], the variable timeHistory is used in a fairly useless way. You could eliminate it entirely and just save the end state by writing tempDependence.loc[temperature] = state.
-- Agreed, removed the former and used the latter

* In the comment "If not, go back and adjust max. number of steps and/or simulation time", the reference to number of steps should be removed since we aren't stopping the simulation based on 
this anymore
-- I think this was removed in 0fee672 (cell 4). But yes, that should have gone

**Pull request closed without merging**
