### PR TITLE
Adding example for non-ideal reactor, folder for py files

### PR DESCRIPTION
**Pull request by decaluwe**
This PR has two main changes:
1. Adding a jupyter notebook example to the reactors folder for
a constant-volume, adiabatic reactor.  This is employed within
the context of IDT calculations in high-pressure shock tubes.
I'd be happy to add Comparison to experimental data, pending
publication of a manuscript currently under consideration (and
coauthor permission).

This largely follows the routines established in the batch reactor
example, and states as much in the notebook.

2. It occurs to me that some users might be interested in seeing
the examples as py files, but don't want to bother with installing
Jupyter and figuring out how to use it (while these steps are easy,
they still might represent a barrier to some users).

For the three notebooks in this folder, then, I've saved the notebooks
as simple py files and added them to a folder labeled as such.

### CODE REVIEW

**Comment by bryanwweber** [comment]
Thanks Steven! I wonder if the `interfaces/cython/cantera/examples` folder in the main repo might be a better place for the `.py` scripts?

**Comment by decaluwe** [comment]
Ah - I knew there had to be a better location for these.  Thanks.

Looking forward, is there a way to make these examples less hidden?  Or do they land somewhere more obvious/accessible, after the install/build process?

**Comment by decaluwe** [comment]
Okay, moved the py files out.

**Comment by bryanwweber** [comment]
They're pretty hidden if you want to run them. They do get automatically posted to the docs at http://cantera.org/docs/sphinx/html/cython/examples.html (I think, they might have to be added to an RST file somewhere first though), and we do print instructions for where to find them after a successful install, if you're doing it from the CLI. The default installed location is also listed in the docs.

**Comment by bryanwweber** [comment]
It does look like they're automatically added: https://github.com/Cantera/cantera/blob/master/doc/SConscript#L149

**Pull request merged**
