### PR TITLE
interactive path diagram notebook 

### PR DESCRIPTION
**Pull request by skrsna**
- [x] Get `Cantera.ReactionPathDiagram` to work interactively in jupyter 
- [x] Examples of instantaneous  and integrated flux analysis
- [x] Tidy up the notebook
- [ ] Merge with master branch

### CODE REVIEW

**Comment by skrsna** [comment]
@bryanwweber I can't suggest reviewers for this PR. I hope you can take a look at this and merge it into master. Thanks.

**Comment by bryanwweber** [comment]
Hi @skrsna This looks really interesting! I'm excited to have a demonstration of interactivity for Cantera. I have a number of comments to help turn this into something really awesome, but I'm not sure what the best way to provide them to you is. Line comments on the JSON aren't really helpful... do you have time for a 15 minute video chat tomorrow?

**Comment by skrsna** [comment]
Thank you so much @bryanwweber. I'm currently traveling for a conference and my availability is up in the air now but I'll be free to talk with you next Monday (07/17). Let me know what time is suitable for you. Have a nice weekend

**Comment by bryanwweber** [comment]
Sure, Monday would work. I should be free all day, so let me know a good time for you.

**Comment by skrsna** [comment]
3:00 PM on Monday? I can privately email you my facetime contact! Thanks

**Pull request merged**
