### PR TITLE
Batch reactor example

### PR DESCRIPTION
**Pull request by santoshshanbhogue**
This is the first in the series of Reactor Models. This one not only shows how to do a simple ignition delay calculation, but also provides a practical guide to studying the NTC behavior of a mechanism, which the kinetics guys study extensively

### CODE REVIEW

**Comment by speth** [comment]
Looks like a nice example. My suggestions:

- 'specie' is not a word unless you're talking about gold coins 
- Instead of fiddling around with setting time step sizes, use `reactorNet.step()`. Because this can generate a lot of data if you store every step, you can do a small for loop to take ~10 steps before saving output
- I would really like to see a second set of *x*-axis labels on the plot that have actual temperature values
- I'm not sure the pandas DataFrame is really a convenient data structure here. This might be a good use for SolutionArray (see for example [reactor1.py](https://github.com/Cantera/cantera/blob/master/interfaces/cython/cantera/examples/reactors/reactor1.py))
- I'm unsure what is meant by "This may not be the most efficient way of doing things; but the goal here is to provide a pedagogical example" -- I don't see anything particularly inefficient about this loop.
- "NTC" needs to be defined
- I would recommend using a format specifier when printing the ignition delay, e.g. `{:.3e}`
- Please include the DOI and link to the article for the mechanism citation in the notebook
- import `matplotlib.pyplot`, not `matplotlib.pylab`

**Comment by santoshshanbhogue** [comment]
- 'specie' is not a word unless you're talking about gold coins
  Changed to species (I was hoping you grant me a poetic license 😄 )

- Instead of fiddling around with setting time step sizes, use reactorNet.step(). Because this can generate a lot of data if you store every step, you can do a small for loop to take ~10 steps before saving output
  I tried replacing reactorNetwork.advance(t) with reactorNetwork.step() but this takes 5000 iterations. I think in the end the user has to fiddle, either with the time-step if he/she chooses `reactorNetwork.advance(t) ` or with the number of iterations if he/she chooses `reactorNetwork.step()`. Unless I have understood this wrong?
 
- I would really like to see a second set of x-axis labels on the plot that have actual temperature values
  Done
- I'm not sure the pandas DataFrame is really a convenient data structure here. This might be a good use for SolutionArray (see for example reactor1.py)
  I deliberately did not use `SolutionArray`. The reason is that the pandas Dataframe has powerful features like sifting through data, plotting, saving to csv/excel which I have made use of in other examples and will do in future ones. So for consistency I think it is better to go with pandas.  

- I'm unsure what is meant by "This may not be the most efficient way of doing things; but the goal here is to provide a pedagogical example" -- I don't see anything particularly inefficient about this loop.
  I wanted you to confirm that this is not inefficient. Now removed the disclaimer

- "NTC" needs to be defined
  Done

- I would recommend using a format specifier when printing the ignition delay, e.g. {:.3e}
  Done 

- Please include the DOI and link to the article for the mechanism citation in the notebook
  Done

- import matplotlib.pyplot, not matplotlib.pylab
  Done

**Comment by speth** [comment]
Thanks for the updates. Regarding `step` vs `advance`: The number of internal steps will be essentially the same no matter what, it's just a question of how of many output points you end up capturing and where they are along the solution trajectory. I usually think that the fixed time intervals output by `advance` are not particularly interesting. With `step`, you will get some points during the actual ignition event instead of just stepping straight over it. This actually was leading to an erroneous ignition delay calculation for one condition when I first tried this because it stepped right over the region of the local OH peak.

Pandas is pretty miserable at building a data structure row-by-row, both from the perspective of syntax:
```python
df = df.append(pd.DataFrame([stateArray], columns=df.columns), ignore_index=True)
```
The fact that you need to make a function for this is telling. I find it massively non-intuitive that `df.append` does not modify `df` (e.g. as `list.append()` would) but instead returns a copy. I can only imagine the confusion for newer Python users and the inevitable questions on the mailing list...

It's also pretty bad in terms of performance. For building a 100x100 array, it's 100x faster if you build a list-of-lists first, then create the DataFrame from that, or almost 10000x faster if you just stick to the list of lists. I think this is actually the reason when testing this example that I had to drop down to storing every 10th timestep, because appending to the pandas DataFrame was so slow. Sure, performance isn't everything, but this is just embarrassing, and it's not worth it if we aren't using any of the more interesting pandas features.

Also, the whole section for setting up `stateVariableNames` can be replaced with:
```python
stateVariableNames = [r.component_name(i) for i in range(r.n_vars)]
```

**Comment by santoshshanbhogue** [comment]
Interesting....

I purged the example of `advance()` and replaced that with `step()`. I like the fact that it can resolve the peak and thus results in a better ignition delay calculation. I wonder why `reactor1.py` does not do the same. Seems like a good illustration of a literal and metaphorical "bad example" 😉 

It turns out that my implementation of adding rows to a pandas data frame was inefficient. I should not have used `df.append()`, but instead `df.loc()`. If I do this, I get a huge speedup

But, switching to `solutionArray()` is definitely the best, in terms of performance. So the final commit a27ff5d13f0f483ce4231f828b907038778b8ce0 is without pandas. The commit just prior to it ed5b7a38e6051b5e9f66a857581b3281104092e4) uses pandas, which I prefer as it is much easier to work with for plotting. Your call in the end

Let me know if this example can benefit from more changes

**Comment by speth** [comment]
The revised use of pandas looks reasonable to me, so I think we can stick with that.

I was thinking about adding a method to `SolutionArray` that would create a pandas `DataFrame`, and this example suggests that that would be useful.

And yes, `reactor1.py` probably should use `step()` as well. It's hardly the only example that encourages imperfect use of Cantera's features.

**Comment by santoshshanbhogue** [comment]
I can look at adding a method to have pandas' `DataFrame` work with `SolutionArray`. Can you spare a minute to articulate it in the Issues tab ?

**Comment by speth** [comment]
There's not much to elaborate, really. I think it would be a simple variation on the existing `SolutionArray.write_csv` method.

**Pull request closed without merging**
