### PR TITLE
[Flamelet examples] Added nb for twin premixed flame

### PR DESCRIPTION
**Pull request by santoshshanbhogue**
In this commit, I have added the first notebook in a series of "flamelet" examples. This one is a twin premixed counter flow flame. I have also added an image to help visualize the problem

If I can get feedback on the whether the directory structure I created is okay, etc that would be nice. I'll tailor future flamelet examples accordingly. The plan is to create another directory called "reactors" for examples pertaining to ignition delay, PSR, etc

### CODE REVIEW

**Comment by speth** [comment]
This looks pretty good. I just have a few suggestions:
- I would name the directory just 'flames'.
- I think it would be better to put the image either in the `flames` directory or a subdirectory of that, instead of a different top-level directory.
- In the image, it may help to label the region between the flames as 'burned gas' or 'products'
- If you put a semicolon after `plt.legend(loc=2)` it will suppress the output `<matplotlib.legend.Legend at 0x114f6df90>` (or whatever the last line of the plotting section ends up being)
- The plots might look better if they are done as three separate figures, rather than crammed together in a single figure
- I would recommend the following for importing Matplotlib:
```python
%matplotlib notebook
import matplotlib.pyplot as plt
```

**Comment by santoshshanbhogue** [comment]
I would name the directory just 'flames'.
--Done 

I think it would be better to put the image either in the flames directory or a subdirectory of that, instead of a different top-level directory.
--Done. Created a subdir in flames called images

In the image, it may help to label the region between the flames as 'burned gas' or 'products'
If you put a semicolon after plt.legend(loc=2) it will suppress the output <matplotlib.legend.Legend at 0x114f6df90> (or whatever the last line of the plotting section ends up being)
-- Done. Adding a semicolon does suppress the output on my Mac, but I get this on GitHub:
`<IPython.core.display.Javascript object>`

The plots might look better if they are done as three separate figures, rather than crammed together in a single figure
--Done

I would recommend the following for importing Matplotlib:
```
%matplotlib notebook
import matplotlib.pyplot as plt
```
--Done

**Comment by speth** [comment]
I wonder if the `<IPython.core.display.Javascript object>` is a result of using `notebook` instead of `inline`. Not a huge deal, anyway.

On the last point, you still have `import pylab as plt` instead of `import matplotlib.pyplot as plt`, which I believe is the currently recommended way of importing matplotlib (the `pylab` import is a combination of both `matplotlib.pyplot` and `numpy`).

**Comment by santoshshanbhogue** [comment]
Sorry about that. Fixed the matplotlib import statement

**Pull request closed without merging**
